export const languageCode = {
"English (US)" :"en-US",
"English (GB)" :"en-GB",
"Spanish (ES)" :"es-ES",
"Spanish (MX)" :"es-MX",
French :"fr-FR",
German :"de-DE",
Italian :"it-IT",
Portuguese :"pt-BR",
"Portuguese (PT)" :"pt-PT",
"Chinese (CN)"  :"zh-CN",
"Chinese (TW)":"zh-TW",
Hindi :"hi-IN",
Japanese :"ja-JP",
Korean :"ko-KR",
Arabic :"ar-SA",
Russian :"ru-RU",
Dutch :"nl-NL",
Turkish :"tr-TR",
Polish :"pl-PL"
}